apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - system/kubelet-csr-approver
  - system/cluster-admin-oidc
  - platform/crossplane.yaml
  - platform/crossplane-providers.yaml
  - platform/crossplane-provider-config.yaml
  - cloudflare/dns.yaml
  - network/gateway-api.yaml
  - network/cilium.yaml
  - network/cilium-loadbalancer.yaml
  - security/cert-manager.yaml
  - security/cert-manager-issuers.yaml
  - network/gateway.yaml
  - network/external-dns.yaml
  - network/cloudflare-tunnel.yaml
  - network/tailscale.yaml
  - network/tailscale-connectors.yaml
  - storage/longhorn
  - observability/kube-prometheus-stack.yaml
  - observability/loki.yaml
  - observability/alloy.yaml
  - observability/flux-monitoring.yaml
  - observability/extra-dashboards.yaml
  - observability/blackbox-exporter.yaml
  - apps
