apiVersion: ENC[AES256_GCM,data:0DQ=,iv:0Df95K2x9zLRKkEyIwIJWBRKAe7EfbRXzw3Rl7PLJcc=,tag:4P+9grNBhVeUY656qFMKSQ==,type:str]
kind: ENC[AES256_GCM,data:QE9Q5LMo,iv:T48TSnQ8JSNJqR9sJNCppDrRuC/eWZH1h6Wk5wta/Nk=,tag:thqDROSbB6yvTnThgRA0Jw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SE+/kCaZJO1bqaJPWpABZv0=,iv:WcAmm/yvUBACAl6h4QJGNqAFUj8EOB1QD+bQNchNabo=,tag:YNa33xyAszKku/frBQHvxg==,type:str]
    namespace: ENC[AES256_GCM,data:SDcbB6ILWXg4PUaeYy9glGo=,iv:7ao+g8KyOADVAHDhTxYPiIjQxTpNovtaElAaM30ZqqI=,tag:+y0iZ3T/lIL9/syd5RShjw==,type:str]
type: ENC[AES256_GCM,data:r6oeNW+y,iv:+jwxnjo355exTBnpstbsrg43Vnqgc2yGopdro97ZYZg=,tag:/3bSPGTLHuzhKK6bUSXutw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:PepmuqUMs8K55nsd5ccRqzVmdYQ0qvrVy20gQZNb2SuankqOBPSiM9j5ejyxa3s31UrouXATn4gDlfVifkL5IwbOUj45Dm3nt/6fggF2L1H4U3hE17OF3a3OzCHRmmUi5SpxkP2LmvzPOyVqfJR09z2wr66EMpaZFcFSrmDofccPYzTkttwPyNo+aRFI309EtxUQzAB1XTuqS0BL9S4osgZ7swqddRRmbIvA/CK02Yaa+VC8zDyYtYO55ODz4Un1GWW1HAb8RivHrL1C5F+BtZhQTa5FyadI2Qjl9InYjg5Z3H0JA3EgVCDpSdPzXl/XTDUTmfE1/PA=,iv:3pthXezOViuc4qAuf31rWW9NdbH5Zak0/Gdx8Kl58kQ=,tag:xUsEz30+Bn4v+e4YywGycw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2M1lheFhTbm5lOTdlZEp4
            SFhJUnNZWVRsV1BUaTZQYi9RSSthOVlVaVdjCnNZb1VJYkwyM1owa1ZqZzVzSUJK
            WmxmbEFBdDZRYy85S1UvSkhsdTZleDQKLS0tIEh4QnpoV3NkbzdjZXdSQ28wNUJI
            S1Nwd1FrTmVzMEV0Umo1RVcwVE9RajAK40Wpp18TVaWhrdIeAaUVJ58XeI08iOoO
            Sngc0awZO9a7zxn1i/v2st/z+WpIMZvIp5GhUDMf2kHxrC47u4Vqag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-05-18T07:20:27Z"
    mac: ENC[AES256_GCM,data:7sOMxbzOhabvlef98K2r1RYFXZzpJT07vqIQo6oekMoHlvy/oTn+GCB1Wl7etLoDSY8TRXLHxrmi9/ePL77T6r7Erw1Z3fAIiu0/7F53OJ9wai/jceu14xsIiw4Ua4D7a8Ud4pRhp4wtkh1f6sZ4QqLNANLJdxlELpEyghvkkK8=,iv:PgIwrMFWXBp5cQuwPBcfp+DLy9TkneHcAVOEshCpneU=,tag:WvUx/S/miRy/QlqDfWFVDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
