apiVersion: ENC[AES256_GCM,data:d4I=,iv:1hOJ6/8Ex/kh3IYlR8UgHwk00B6HDHYYcwjTAdXAJ8o=,tag:zGWAQjoKJfXVybAbUqwPmQ==,type:str]
kind: ENC[AES256_GCM,data:ZXPgX0Kk,iv:RTMqFtJuWkbxgKVsqWqGszthwXlppMYCyoH+qng+ebo=,tag:uQtpfcvMtKkS6LTCyct6EQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EbcxBev/Yj2h7A==,iv:+6hUI/EEvFC/KG84LDuXAwIWT5RHg6l1rzZNHUoKJgA=,tag:eAVUt8ki18kvFGYPsov/hQ==,type:str]
    namespace: ENC[AES256_GCM,data:bVkGdKNmtQ==,iv:T1jq7d/YuIJ+e7eC6CzBPzsQk0368RNbBckFzKNvTc0=,tag:4poZLN/epDhgAAuwXtbMHg==,type:str]
type: ENC[AES256_GCM,data:PFiQyRNU,iv:1rx+eToto6UWJ8j6GeIo/GFJyAtMR5kqGHwcR/wD7sY=,tag:wG5ZwohHnQ75gjcMPbFXgg==,type:str]
stringData:
    rootUser: ENC[AES256_GCM,data:GWvYnes=,iv:42K/GmSIfw29JL3Gb6AjcCxaip7QJzchVWuAmlRsbvY=,tag:QstPWo8D2lHZCnN5ruZ/3A==,type:str]
    rootPassword: ENC[AES256_GCM,data:L53NFKeQVizCSJBuJkODhfdCQ/RCrtKx0MLDUF73cWQ=,iv:8TTcXa+1E1r8pvTZrOpO9ZP/mhCx/HgICH7T91lmboE=,tag:PzG6RlHOUi37EPw2C/IBZA==,type:str]
    outline-secretkey: ENC[AES256_GCM,data:VVF4GnHOfgj0CAuKdmy4RjqZ67XH2oDDZN0hc8cC3yI=,iv:k0WE6JQxoVktc/8BaT/Bpftxl7IU5+4yYsF2cU5neJI=,tag:kJvNrWbkKcRYh6P2mPjRKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYkVCc0NIUE1YY0hyNnN1
            dDZUa3phektUd0huRnNzUkpRR1ZONW1wclJBCm0ySEUxcklMcVdsL3dHdXZiaklU
            bmV3VlBienBjTlJWVGdxV3gwaXRDRTQKLS0tIG1hcWJUL1k3YUFkTUJmN1dnQ29s
            OFJxTi9SYm5mSERzWVZYdmVhN3hET2cKJh4hNI2Gj1twVa8QWp3aRKrAls65cvC0
            GFSQPZ6HyLatSo3LuEmk33dAzUR4J45TXBys1Wu7jVrshgwUUjtQ2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-07-18T22:49:41Z"
    mac: ENC[AES256_GCM,data:q+Emt8BBLRSBFVVTjIdtUZ5wMlo5dnpwEW7kTzq9maes7+okWsHOmNdca2jlA4GGeutt86dKEAtS6oE55EQb9FyvAaEFKyt4luBGIUQSFIf0RTiiBpZ4LQ2lhzslXNY906D4nTGTWeIvwUnuI6qV3BQnX6yq6I8ZnKDU+cWcjJQ=,iv:oZxKT26JffiiiHQny08xUbx09kngUs75M51t5+9X/+Q=,tag:rQDAONJP92U6UFuUkxP+Ag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
