apiVersion: ENC[AES256_GCM,data:ZuU=,iv:NTqHuzUbyxjJbCZz0jQQNmfDptBhemlVXZDiB2woldk=,tag:LyvqRroI43Gb9GwHA7zr/g==,type:str]
kind: ENC[AES256_GCM,data:XEb8DomS,iv:c0q9S38HjDEuwN/8QUlyvW8AkKy4y7DZFD3C+gqHnug=,tag:MuCha4R5zS8X9RY8R3ZkXg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wGacOrIJHoHB9EdIWgq6,iv:vw9vX3/UHw1EiDuvfZgPDRkOKO/VRq7ckuWS0fpUJYM=,tag:jYhx4awaOtq85SSgUumLfg==,type:str]
    namespace: ENC[AES256_GCM,data:ggxRc0QUKbV2tg==,iv:bWcPU7rG2XjrwTMJWc4FOZjrU9r2NhPojg2S+2h4Dio=,tag:9zMIy32trItrke1PMeILhg==,type:str]
type: ENC[AES256_GCM,data:EzKGmfmo,iv:8KWFSzm6OgK2tJJFICPm6Vp5gxAEkYIcHk3hBmJSzkA=,tag:oNAkFOLJB/06jUV4HmbCNw==,type:str]
stringData:
    webhook-url: ENC[AES256_GCM,data:bdLZc9rYsNSkq352V7OLyFt+BWm3KOoSgH3S6Nz4CXSpW478y1Z4K2lQjZiLOYspHhm+ciZJ29/U2mRJHTS0S4p2kSSQGxo4CSvUgimPadMHdjFYgppxTRk36hyWdeY+Yg74nFyH5lf6bQgYqlx30jyDEaiv0PNoTw==,iv:hxZsp51juixsDzwQ/b/ksRwoGNex7uKXsgkKk5B7b+Y=,tag:UpyxnO6IIVO4LTW5jVrwiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqckJRNytMTkhYR3d3emhJ
            K3JDMStOVTA5dW1pYjZabzhNQU56TEJrQlJrCkdsT1pVWEZEZlZFSlZjT2o1M08z
            TmFCWnNncjU3alpYNDh4UjlTT2tTeVkKLS0tIGNlZnIwNmJUVjJQUkhGTktGd3RH
            OUVUTzBjTFFXU2FiUmo1TlluVlgxd2MKaWy/Ef0kDVSsdQ6AHndUX2HksZRGJ0yn
            emv+rww5uFmWEk536z8UOA2MSJXDxYmyU0k7KjUSuFOd27/4AYcgiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-05-19T05:27:24Z"
    mac: ENC[AES256_GCM,data:K6trXPDS1PgokphWVATdj6Gozxv5Mr2RFzxAOvuITX9BFC+ZVwq9CraGFnDmfFTJkfaXN1SDZmE7AF49GfmN5xEbJIK4P1sgR65eF/3cOMKnB3UV6K6asPOrXhDq52CRc/ggTqim4j6tg388JTU7MgSyDPEiAg6k1ifUi2zICh4=,iv:Pyk3qmvKH97zfWvsaw2yLxnpNr7btHzfTNCkxmYkK1o=,tag:KItQZb+lzzhdAJw1y6wgzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
