creation_rules:
  # Talos secrets bundle
  - path_regex: talos/talsecret\.sops\.yaml$
    age: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0

  # All secrets under infrastructure controllers
  - path_regex: infrastructure/.*/secrets/.*\.yaml$
    age: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
