apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-data
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
