apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-assistant
  labels:
    app: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
