apiVersion: ENC[AES256_GCM,data:fpU=,iv:cFTXQ/TLA8M94cqnzUiDKwa9stlrt8h9yslfIpYRTSM=,tag:njroJqf9d3N26dm5KmV9EQ==,type:str]
kind: ENC[AES256_GCM,data:wHibDJzp,iv:dJWVufuskB3C7xVCN3f2pTOiP/aKrgr0wdiWHmUkAQ4=,tag:+O3bTBUKVXApbQgAycAlFw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SsdQ/L3pHnkClzosxutpNn2/ZiSK5A==,iv:5Z0tRiB3KmpOaJqZxjMAhkyP6dhNCIycigpYusvoyGQ=,tag:WQFn7NNwIo2EwSdZorVG3g==,type:str]
    namespace: ENC[AES256_GCM,data:IO1bDVw5P8+acjhrKLVD6FM=,iv:ulv02oOl/+7t+e/QBNqsh8jaIzSLhu8PCJQL5p+bMkI=,tag:pk3OOMN9tVGMJGG30wY9hA==,type:str]
type: ENC[AES256_GCM,data:npbeAY5e,iv:NHJkbJ9yAoRo/Tak/fnYhPGDO1R0TftnZkvCspDRtHA=,tag:Bi09A6vOfXG0nGNvih6BtQ==,type:str]
stringData:
    credentials: ENC[AES256_GCM,data:ISnIzHIJDzyMroJXYNqeWVvUKm5namTMEPFIh9HDDUTWvKSjLxOIETGqzyxZ3woKLQ33trb7mh+22rpEKwENQ5JQTFP1DwG49fAP,iv:SvaIE18KUsNV4FBtMUwZgV5o2LNZyUbSNRYjOQI/OS0=,tag:6AfZ8Rlkw5ytHMzJHrp2Vg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV2ZDR2pPVmRmTmprQlpF
            Y3JVYUdvQXJJQnBoTUVZNUdQeUVqQk9lSkZzCjMwRUNEZGQ0SW1mRzdqY1VhWTdT
            TkwxWGlnWkphNjZwUjBUZkhRRFNTQ3MKLS0tIC93V2FmNkRsbW80bVlwK2R3akZF
            aUp4WGVjb09XYm0rQWJDeUpzM1AyQm8KjwzjTx8yd6VrDXKktxsuPwjQCvnwv2ix
            eaV1uKG6j/8SAPH1II8ZXHxtkecZ1gUDVUZe+a6SW7ZQuz2YUrrDZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-05-21T04:19:43Z"
    mac: ENC[AES256_GCM,data:22qGoKxaA379TOnU6zLDxfrd7Zf4ZUXotUbntDiEbNT/3z0xoO3/RgO7GWW1IN7HOSh3fv9L8aGeYVsYqDa53jnNXfZfIzoxaVK0T57sAu7RZ7CtgKEqwb6M8ZQw00OSGjvtyzf0Vva6NCK8UWcUzzQ0BCPG/qufsHdqMbr/fao=,iv:JOeYp5VL+ggL/wc7g58JuWjMRggJWXAcDmBJMTeS94I=,tag:VuxlZN6mRgAk2PSFoCXl8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
