apiVersion: ENC[AES256_GCM,data:MZs=,iv:Ya3IBVw281/Dz9X1sxrdb2YXdjDDAWl1KzUOnLKqVdU=,tag:tQbPMCl8Av7lxccsm9Wegg==,type:str]
kind: ENC[AES256_GCM,data:vaPCTgbq,iv:ixbboBiJeEvM41hIhBVnYqgbNXbCKKocJ8RA9x/Yjh4=,tag:PDs8b1eXBur1ntRuxUfOPw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nHKtXpL0sKe4,iv:UGb8BnxjKY2DpUqdbq9+BcUQYYhqbeUObbyELgJcv08=,tag:9Oq25rRJU+YTrWJTx8D0CA==,type:str]
    namespace: ENC[AES256_GCM,data:R5SGIA==,iv:yXsnIS455oMeJKE3yMZOZFuxwT18EhKjmRAJrpi6ffU=,tag:k+LCH4IbfXkQ1t04V5azgg==,type:str]
type: ENC[AES256_GCM,data:WbqyqF/m,iv:7S78JLNE6cCi4nmwL7Z72prRNzYjnBGfQJ94qU6QReg=,tag:9y7zW4G2JNSDy65OTolygA==,type:str]
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:ED8Dj5ZGIgQk1AOyWxrECBrRgSvKlwX2chMeyFZ29NhSm8sJtty+6PNL0xY+m7V69Jfead6T53eOwpoNpwslUE8aXmXDsGGD,iv:ra6PP1VodWwaeC+bNv1LbwXSMW5bPlKbvjDE3vB0gZQ=,tag:kulUxHc/qgdBBVmx11y4mw==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:3SMAJBjyD+d04oZHHc6fTxq7rRvnwHRfJf5Obp4XjPtPP+o4dIwOgG/Y,iv:gOWqaMtm4IwBb+XOkNnRd16ftjP8R21UF9wvq1xft+M=,tag:yZx9UsvrSa/rNkhgZ7ByWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPV0F1bytKWWJNN3N0a1Ex
            RjZOd01LOXZQRVNWemdQOFlGNkRuQ0pjaDBRClFIYnJTMVYrQXVCcmN4OGROKzVu
            U1daTzRDTFAzOUE0NVBySW10TlIwbG8KLS0tIE90amw1Rmg2aFZtK0lBazl2dWNE
            MzdSZmx0L2pyVzQyRU9BYlNkcWRwcGcKA30HGTHDiqVTwwn8Z4DsSZbnV5Lmf1Pk
            28sreh6C1q63FEu99cBres9WfEKft+vBVT0KpvBiLagwV2BNl61bFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-08-10T18:13:35Z"
    mac: ENC[AES256_GCM,data:TnUA68yVo3RnpR64vJ4x196Yi6gTNxnDjCUw57MXTTqtIMYYWeNdhl4ecYn2vCQsEDweR5yBWg7RHKg5nZn4vKo+m8mbyuTf6NXjEJvyKSVt98zgiRQ2DZrokW1XAo5CVqhMQHlB0f1HlYVwouOzHASlnpndVFpyigOjUFTpDJ4=,iv:A8jW9zZAcSvo8T+MCOe6KjE2w3QCskiGyFHfHUY3C2o=,tag:vvherKe29iVck1IzHBAiVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
