apiVersion: ENC[AES256_GCM,data:dao=,iv:WnwV+qc3h6JClQ3a1DChMfeJ8zOZSq+LrDPkU4tFkF8=,tag:cKUrxIS1J7k2wfEhbYU70A==,type:str]
kind: ENC[AES256_GCM,data:ZZQT5FYu,iv:l731UAnBMqeM5eLjokXvoCn98GYbpMFhETMxj53B9gQ=,tag:lDI2qjUsvLdb2kPDlc1Inw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WBXuWE8wcRixoisIIBVUY5MLWGw=,iv:7GEeES75ZSPmMy7Uwdvw5gih83dw8gk4Pk5+Aza2kVY=,tag:LDR2QyLPPZqBfu5oDt0/og==,type:str]
    namespace: ENC[AES256_GCM,data:om4V5BQsrqbNqgAL,iv:r3N8PJyOK4iEK/iu9pv6kQM6PD4ezSm3aiNuwrSRDqg=,tag:aEavkh6S+Hzarprhah5MCA==,type:str]
type: ENC[AES256_GCM,data:1o5dK+i2,iv:6sVnDGdx0yhoPFXtuXO9gdL6qrnJ2GhGw2O36OhNzb4=,tag:ha8NTXy4/6hUNspCQ4j68w==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:qoqjUZWHenWKo6TRWquHSNBe7eml9TV3i6Y9Ie3D5VPZ6Gi1ahtzgQWeRO+ZPs0Y0S0LFQo=,iv:hzTbp6jdNj9nehwLZ+A+3oSsURyFMlEey1IUIZ0aXro=,tag:mmWdZSYW3lYYNCar31nMUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z21wQmt2akZBRzUrZHVN
            VEpJY1hFOXlYTkVWdUFSQjBLUWlrV0ZvdTAwClY5SVZkWnVIc1F3dk9ybFZUUVhS
            MlR6cVdXWjBTd0FOdm1NbVRmL3pIdm8KLS0tIEZCLzF2d3h4VUFUMWY4RDVTWUJB
            RDMxdFBaak1iYzdGR3lWY1RPeGFGc0kKc0RGRhqaPzubffdOs23cYBwqCzlKVUoq
            AQTVtG+9LfQ71ulLo6Wumfi9wBzO7vunxD8uAY2q4Je2mDXSFYlMMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-05-18T05:19:07Z"
    mac: ENC[AES256_GCM,data:s22hzKRWPZ6d3JyXr3dlMXrTRTorrmyR2E0lZoF+M3Rc8jAI4Z0byC7F2nJ17iUxQNfUIk4tXESRouo9EuW/PwXayT5zBFznHuYoGTRFtPKx2K1K70JYoIvc5j0nLLg88a+ymBJQg+45D914lCOqWqMhDRiHIOHUjRAp4IjnumA=,iv:jpdfT0E1AVEzrV1qD2ypxEa9g5QqjeKcWl3eAyjqKV8=,tag:gfazsuDZ7egMC2I40i7cqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
