apiVersion: ENC[AES256_GCM,data:GHU=,iv:IMmRq/F00ZJRQjdvOwSYLfT153797UsR4UNn/x7ALzI=,tag:NDzli5ivHlqumQ2V38108w==,type:str]
kind: ENC[AES256_GCM,data:nbr48ndk,iv:fN/ITKcxGmjR1pFyyHv2JnISXQB7BaduMlF8Th6BIZc=,tag:econjLTbCJSzyGKwAK3XJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wQKhizJV0o1DEtE/WA==,iv:B5ub9PNQomDOxEWxB+X+cvO+mhfBG9cwyLqmETYXPi4=,tag:gJijczGndwyICkgVSAqZyQ==,type:str]
    namespace: ENC[AES256_GCM,data:JRFT7X9yitE=,iv:+76TJVdq4fth12kEY4ng7UFw3H7AEQCMAGG0UxrBEMg=,tag:srK0Hyv6g94tjJpw+NXt5w==,type:str]
type: ENC[AES256_GCM,data:NIJqMGj2,iv:WX9lGCBhSfLf1yoSHETBSKZJQmhVH7KG8qT3dNMy7D8=,tag:Ld6ZqVqXD7Fd1iPIHPsuPQ==,type:str]
stringData:
    clientID: ENC[AES256_GCM,data:qG7oIFbOjQk0vBI6JtRpZSPlAwwAc/F+o8xdWOIeSNsVo3qvjr2oiT4AwxY3reXbne8kN74CYKbKMfCORPpWuQ==,iv:WeohwbCZXtuovEXr06VulqUYndhh71ZAIcFx5VoARPw=,tag:P7MRhdJWIZFiV3I2gHQFww==,type:str]
    clientSecret: ENC[AES256_GCM,data:U6N1K31lylqaf/Va1/TD6323eMvBSvX7tjgypa7n5R9KIHARiDIYqPOkmPgte3LEmJRBFlx4gdvFHJfEKQLTvQ==,iv:n8AaLZuhfogR29pcrSaYyPqHRg/c1SrEXCXpt7F08T0=,tag:tH1i2AN6b2u1dqVZoDwmEg==,type:str]
    issuerURL: ENC[AES256_GCM,data:zg//ZMpPTW/J+XKYPY73C0ZYcqB2RVx3/Katlsfdm7X5SMMw4VJGaCU30r8Y2jn2V2LfFi8iN9Ju0oz4LSyodrJpIv62++BY0q8++2izjprtmppIjvIyUOQ1qnf17ccr38PhK8kTY2MN36SfHyaUD3/nvI+5lN0OjWmnG5ObVUiFcw==,iv:HdDoCmYUkjBQnSyGVluIxvDwqS/RiCuWOYAOGj7ZyzA=,tag:awbCP48kxxDOlcjgWLIvbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZXB5TlNoVjdvZWV2eVBT
            MTVMYTlaTjRRQnZnd0p4RHlFcEFpeEx6ZjJzCkE2aVBabkpPRUcvdzBNQUt0VjEv
            ckxwNkhudGlTaFNUdzZTUlppSk5QbjQKLS0tIGNEY1o5V1lEVTdHei9hc3BNR3I1
            a2RHS1N4QnFTcGV5S0xwb1p4czVkUWcK+giujKtp3p/fYoSam1QhY6q7Di2jgtDm
            1nr3v5ItxSqLKhUlWmjovqXO2YeScCJYS1MHob5W+mttKavV59E3JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-05-18T23:56:35Z"
    mac: ENC[AES256_GCM,data:Zxso4jN8PkNDkj/xwgeB7d6Lf6BNbccvoGQ/I6siCroRyhtYg3gIxhFJUD5AbYad6DgPurePibRPKIxNh2Ludyd7aafpFhOm+2R8X03IkoiF1qft63QABJKWW6oBgDD22cvAtNIIzgLc9Z0juefVdjYMu4oCzRG2K0jWekF7O64=,iv:bmioOcDsVdKke2xeYG1dGPDlP8ShiVW/GkNjd1EOwXM=,tag:XAXDiJCTUZecUj1nBItVMA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
