apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: gateway
    - name: longhorn   # Prometheus / Alertmanager / Grafana PVCs
  interval: 10m
  retryInterval: 1m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/homelab/observability/kube-prometheus-stack
  prune: true
  wait: true
