apiVersion: ENC[AES256_GCM,data:ANE=,iv:Pf9oQfpUP08eARen3AHnT/7x1SqwmPiEgdik9+QzdnY=,tag:Z2Mj2l7uDSz8nBXP6BUuYQ==,type:str]
kind: ENC[AES256_GCM,data:UbeJ0szW,iv:hNCFGH4MsyxNh++6sy8Sbz3IMdoDXHPtDK5MwWfSapU=,tag:B8SeCz59ULirS7GAuVWN7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kIAOwyWA44JSfg2Vhwv5ggPC,iv:iBWXCyDX226rlBx5M1K11FP9XMMeRZQf17Yej5o9REE=,tag:ol22RX/v+924s88fuwvuBg==,type:str]
    namespace: ENC[AES256_GCM,data:tHxa2AhYsQ==,iv:KDgDxRxJVIeV3KiQnwFzQIG7rd7zV4Xtm8jl4bPlB5U=,tag:zZvFrgbYfA3Hx+DnE2dcKA==,type:str]
type: ENC[AES256_GCM,data:eCM0vh2g,iv:pWyD7Wlg/PSeff1PMfmMl2aE3wgLyHmAVw0gfiSFli8=,tag:Ga9JlTcrxa/FAOUY5tKZuw==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:k/NuNLMRZHBysyTY5KvMRkwZmtIHQmRgfGY=,iv:KoezkHXtNinWDoZ0mPqZKKErW15DRoGAE/PZ8n+rKSE=,tag:r4eyeGL4XN1PGLAB/wOOlA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:cunr7NXuI7oKBWmxQ0qEkR97ce32BiXfYneiTiTiztV4/brvpJ3IclO9kYz+oUAYyFXhn/nJVTnqDupevUbxSA==,iv:7LN/8fXhffaikSXW9D5ODNi3exvA6/vWUX/TYBBudDA=,tag:MrdIm789ZsNbY8ft39T/6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV0tWLzJWT0R6ZnJ2SHNF
            Zm8yUUZSRU1aY0FobjlmaGxMNEFjeFFUb0VjCi9NWEl5aHE0QW5nQjAyckFndmNt
            UUlJWm9RRXRXK0VtVzJlOERtdjVEK0UKLS0tIElzZ3dLNlllcnBUOGw1cEpWS1hI
            d3lRREdTZUE3TG1ZZGNVZUtJWTdpalEKHDZwVOwTcB0Exrf0FBxtxNJnGsY69Evd
            TUhg7QYm/klfr2CKpIn2ZRbm0ir2pyjq39Hk2JaJ+x+Q3/beGS22lA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-10-07T03:29:56Z"
    mac: ENC[AES256_GCM,data:lJRIPseR7gY4Q4/BcL1jIEnR+DHLl2S9b/HwOO4KaMi0Yp7q2VKZyukCTACimtFgeP4tBFnSh3ICtZVz4vvGgVKaNVTM7HlJY626RVcFk3ICuyrvYl8oHohh/JsZK5y6ltwyLPBHXiR6bUC+F8DpKgZ1pYz78ZGA5EU6FHqv+4Y=,iv:Wo46MxDy/qFqNC9P87+yjP8SaBRDz6hJv9UjT0i5xCU=,tag:7p/4T4aZeeLAb7HdF6Rw9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
