apiVersion: ENC[AES256_GCM,data:gg0=,iv:h1J4RiNrE9Pmu/7qALafqYvouhrVySGWpa9G/8d5aZY=,tag:QLWGWVZ8iNS2FcXmtRzApw==,type:str]
kind: ENC[AES256_GCM,data:16T5Ypf5,iv:tK1iWTlrKWnPx6jvPD/KO/LjsWz5rQJxlTSYU3SDeOQ=,tag:Nj97mWw/3acgkWmeXAqFXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ReO74gAdjlHBMbInreVpbWo=,iv:I14J//VIJu3lR7wIyb9uGbKrvI/Q7xsVHD4/1zUlbkw=,tag:+Fd/rG8RPwgYfnNgkoanAQ==,type:str]
    namespace: ENC[AES256_GCM,data:N3B0pusKug==,iv:E7bY0lTSW5zvAXFQrFS0eVT+cJVrATWGc7WK4ZGmKak=,tag:ydmWn2z9BuC/kJiOoO7U6Q==,type:str]
type: ENC[AES256_GCM,data:A8C1XAer,iv:dbF+D5iy9MOiKbMFoS34dbc4UoK6W1S8rXF8RD+0MDQ=,tag:zmHlhA1cbMrXu+8AHhhmig==,type:str]
stringData:
    rpcSecret: ENC[AES256_GCM,data:KW6vd99mu/62E8QYxYtCnIrBMSBWR6sLQ5+QfqEcCAYMGg1mI3DV7ydiXaqT7UvJa92jvw4pSGXpJRfli5v2EA==,iv:+cjN/ldY2eHk6fzDkISRcGMErBY9U3S8gN9S2Qvd1rg=,tag:NqdfDsrJl4wdH3XiIglo/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MnlKcXkzNERSSUFiU3Ru
            YkdMVmhJUEtuV29yZDhINzI3clZrbFovSGtZCk56ZEVxMUw0cVpSRm5vdFV0NHQ0
            dWxhWEhXUWZncisrU1pFUHRQbzRRQWMKLS0tIHowQmNlSDhVS3BiZklVRzJNVHJt
            aUtWM3ptQnlsUnk4LzJPRVVjVlkxalUKg/SNr6kie79Xo1gBZza4cQ1eVoDnZNJV
            FW5odRLIs9iI6FQTPO8NKu0z6xeJJH/fZbPiZEq7Rps+kPL5/t93wQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-10-07T03:29:56Z"
    mac: ENC[AES256_GCM,data:0fbZpLIoBl3b+sif7Z+Z9+zq7xuZVm3+sq6+tbEMWydtW35aGY1xpiAEeamDBJ/fa4cVglx0QwXPJEHSUK/JvlaarTVDbL6jXYIWbNRNEiMFTnUPTJ0MHSi11Rw4VkTamnghZC9vxLH71wGoucxvR0xV++q4zExVNcWprEu/7X0=,iv:gnvPC3vqGrka1dlz4LKNkZrIBwDWHfIE/Pwhr/YReQQ=,tag:Eruzx0G8usw3zTvGlq1nxw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
