apiVersion: ENC[AES256_GCM,data:0xI=,iv:NLIEGVGPsXyEg7stHDx4dGxv+Eu6bLOR7sRvPUfb6pA=,tag:FsX4OhAmfGQyFBOTgngekw==,type:str]
kind: ENC[AES256_GCM,data:8/Qrp39Y,iv:BmaBBtioyU8woPQpYiSDrXSWEMm9YXx0mcYi76sin+k=,tag:P1GT6/j/O5HkEZxLdtCxeA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BoQD16KxFimPa7dzaIhZ2IATsQg=,iv:TdGFpcqNvpCxxzwZODcY4pT3rQYxrDU/h9bUPgu0ufk=,tag:z1xgLTXec4CNQQCgzspb/A==,type:str]
    namespace: ENC[AES256_GCM,data:EQObPGW0v1LKZ6pb,iv:DdssKK1u0DjXLNGO9+bnlTUkQOuzfI91in3Z9tfWO+s=,tag:bGLBcVj7PQbd4GFiXGGYGg==,type:str]
type: ENC[AES256_GCM,data:YOh0qkQs,iv:CHnuyzt5FKbBxQ+iZ7URBeR2DVYGAc+sFcpe/ka399M=,tag:SvxT7V//o5dhT3E00UWinA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:b6tauj9PiTeIs3a+a+ypRqyWWEV10zA19c/fOJkMSCdCGzi9Fo5c9jEYLO2cfwqIU/TFr/Y=,iv:OXmQYm2q25RjqL6IJHBn7aZ15DOXv2Eu7jYPQuE6pxQ=,tag:ReI0d6qKV9tjJJ5VUbDkKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZVF1b2lIUFVURUtDcWFI
            M0I1M1NwTFdobkNhd2RMaThXV3E1ZGIvMGlJCkxRLzdXTStiaWEwSlYzYkdycHRT
            UWgySkF1cEozQ08wbytpb2d3OWZDbkUKLS0tIGRuSkEwbFdBc2xHVmZIZE03Wml0
            bUIzTlFnVndURFU5d0x0bUYvK3QvMnMK42lRU+aqVgP1TKIu0LcfQLiZSedS8GNG
            jL8Ivh/8Ysqvdh5W6oTCIS3rAIVzqDLiGqa2ZzRekfCN3eGngrCvDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-05-18T02:56:10Z"
    mac: ENC[AES256_GCM,data:htQRrNIfMpxcIwSH+A/1fB0xwoCdS6GkHYncVL1lrD8YllUzFT646pQQIYr9jOG3Zt44h/6n/3K4yLC6iPM2zY64VQgQFQETch9MrAPytIRjPCQ9hOdtpA+opRLxIr7qeO+GUbusyNtSRWt4xE5iu9bivd7HHMQ+nRbV9T/tMEY=,iv:T7zpChS7pxglsXGWymXn13bhGdufnj7KKatKPfk46Ik=,tag:ESva7gvfW+ohloQ7YJMIrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
