apiVersion: ENC[AES256_GCM,data:EgI=,iv:Fmitg6mJgrw5lbaJxO+YABwOpHnTw0t9ik12lO8bm/M=,tag:cMjlPdilPL8Hnn3sGJtAqQ==,type:str]
kind: ENC[AES256_GCM,data:kCRLDasN,iv:RzHR2zFpzigg2htNl03pxinYtkjASqB8T1lG90cWMQc=,tag:W6aawko6D5IcYF4FuX9FUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:k49cy3GqLfajKg/+5oc=,iv:u2q3JQjOXLHAm0BuVQ5bvvIHzKtPmmZwjQRb+h/5GKU=,tag:ABYgOd0aXt9d2RPdmxMtbg==,type:str]
    namespace: ENC[AES256_GCM,data:qH/Iw4ff3HEQ,iv:lnidYs5FbuWsStUx54FJ8i176InBzZ5u/gkdchKA0P4=,tag:KBYLFjduY85nwZbimnVyOA==,type:str]
type: ENC[AES256_GCM,data:ppmqlUun,iv:P/pA8c7s2QIyEMl+7yM90JpXbgCxvg2uKaicWjJ0BQE=,tag:lUBnkfsPtl+ZGOa0W6Fn0w==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:VWhSVKDmaXwpRAaMhv4di20=,iv:HZmIYVyVIRhcVt4z9N3aFxPM9YS4t/1sjT4XD3BAoyE=,tag:XxZeKZCObLaCW6Cyv5Snjg==,type:str]
    client_secret: ENC[AES256_GCM,data:CzIoA5VD8vzofmQEHEjLpnnfqcmdHQVUyB2UG/xykAbayldQWYCR8p5GLnI3RR6HPoQgpoyiotLcqGfciGcm3Q==,iv:AXyeVpvr1v1H1eEuidImHyJaFi/XZinlwNwbW7+pRis=,tag:2t79CTfCRJZruy7A09Br9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa3NaRThjV2pnRElhZ1JM
            V2syUEV6T1F3b2h3aEpLcFh0VUU2MTd2STNRClZ2RHFQTUFSc0NCaDNNaFREOGxO
            d1BFZ0NsUGs4VGRqQ2JVNjV2YU1QdncKLS0tIFZRR1dKSWVOMDdLbkgxMElSU3A2
            SkpyRWhRUkZwN0ljOGE4dVJVMEphekEKJdqS9jOqxjnl0TY+dplt7DEETd65GiU8
            XUpD+nC0AuqaYnR2iUwyqAdAIsIL7GEVbp2GOTAh7ETgAzDfqnyxzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-05-19T06:52:37Z"
    mac: ENC[AES256_GCM,data:NJSzrt4d+cz3QqIRoS37ThX4DI1aFBJmBEKXjzkmkk4gN/HVifnT9JflKnFLVxMYqL3s9bLaY22A6fzK4p2InrlC+0ac11NT2O6v/5c8tv87KZrgI12/bBmuqzg6EzScE/1PbLrfs+yA10yu1OPLYyIUbDZhYGvx8tyAg1G2OLk=,iv:XnOw1JRyvDe0BGR9Q9GpRbF6yIZ2/S1TCgVhPM6onYI=,tag:Y77xahxgTuPvKsUJZjIJLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
