apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy-web
  namespace: appflowy
spec:
  replicas: 1
  selector:
    matchLabels: { app: appflowy-web }
  template:
    metadata:
      labels: { app: appflowy-web }
    spec:
      containers:
        - name: appflowy-web
          image: appflowyinc/appflowy_web:0.15.5
          env:
            - name: APPFLOWY_BASE_URL
              value: "https://appflowy.tylerrosnett.com"
            - name: APPFLOWY_GOTRUE_BASE_URL
              value: "https://appflowy.tylerrosnett.com/gotrue"
            - name: APPFLOWY_WS_BASE_URL
              value: "wss://appflowy.tylerrosnett.com/ws/v2"
          ports:
            - { name: http, containerPort: 80 }
---
apiVersion: v1
kind: Service
metadata:
  name: appflowy-web
  namespace: appflowy
spec:
  selector: { app: appflowy-web }
  ports:
    - { name: http, port: 80, targetPort: 80 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  namespace: appflowy
spec:
  replicas: 1
  selector:
    matchLabels: { app: admin-frontend }
  template:
    metadata:
      labels: { app: admin-frontend }
    spec:
      containers:
        - name: admin-frontend
          image: appflowyinc/admin_frontend:0.16.5
          env:
            - name: APPFLOWY_GOTRUE_BASE_URL
              value: "http://gotrue:9999"
            - name: APPFLOWY_BASE_URL
              value: "http://appflowy-cloud:8000"
          ports:
            - { name: http, containerPort: 3000 }
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend
  namespace: appflowy
spec:
  selector: { app: admin-frontend }
  ports:
    - { name: http, port: 3000, targetPort: 3000 }
