apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: 705038a6-3c96-4250-97c6-b0ad6439f62e
    no-autoupdate: true
    metrics: 0.0.0.0:2000
    ingress:
      - hostname: '*.tylerrosnett.com'
        service: http://cilium-gateway-cf-tunnel.kube-system.svc.cluster.local:80
      - service: http_status:404
