apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets/auth.sops.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - service-metrics.yaml
  - servicemonitor.yaml
  - httproute.yaml
  - networkpolicy.yaml
