apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data
  namespace: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
