apiVersion: ENC[AES256_GCM,data:lCU=,iv:cQKHLNgsy5yJjOkWGOM7EuIUfD56xNP2SrjocaZ8Eko=,tag:Drt9NErlVVP2m5RFtJHASg==,type:str]
kind: ENC[AES256_GCM,data:s8f3iGXz,iv:Wx5pkGyQx4tmn4JtQevuf5hZiXDHSh0MboRiru7MmHo=,tag:FA64fGdd4OdpsPwhugp1tQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QKW0UrvJCoYGYg==,iv:LWFAo2b0J0uTIloVaRIbzRPzpxMFI28Vs3Afs7LAXoE=,tag:4xrQNDhp6YgRpSxmOn/geA==,type:str]
    namespace: ENC[AES256_GCM,data:imS2vqA+4K4V,iv:GIuy8W6Io7bypR7ZTZQY8n//e6P5mx0JLC2dLqVzX78=,tag:EKOBp3jeOVDm9/g2QQ9SXw==,type:str]
type: ENC[AES256_GCM,data:MxLD2QAH,iv:8XDp2vRZiFCVY7auRWLieM/qgYtaonDecXfarr68UXk=,tag:cWJol1PC/uRqaFoxoh/65A==,type:str]
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:jkKlIuww9E2KfNV7pdFr2cVYEhiiyUtFgtZI8BtkYkYhrmCtbsjh/deoo3ae28PmykhbJOwFBhqb2Rjf,iv:9nhuazRlFaOKV++ivSKbxevqnC3lyjOLt1IsPK5ltOE=,tag:Ou4kX1CMLcHekPhfb13ggQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN0ZSUVBqK2tTZ2xWS3lo
            R1BVVG16YjFqQm80Ty9KaTREeE8zdVpKQ0NzCmRobE5MbkgxOHlOYnR4SUcrclJO
            eGRpWXc0WFN5ajg3TE1XajM0WENnUGcKLS0tIEEyS2tyQWVwait6Zy9SSUYyUGJS
            bUtQWWZ2U1Z6YmcrSjFPMnp3djZEbUUKT/gjHwvRMyFrtW4cwCGq8zg//BoryLy1
            R4HQLcqCmyz155zKQPww+x97taj2CAuDr5wWMYTakARtFzvq3wvXIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-08-02T04:43:47Z"
    mac: ENC[AES256_GCM,data:W1a/R20AMFdkUFPA/rmGPEprnVnI/MX1mZ/mq9+5w2mvV3aMyVA31koFXXakkC7jnSx/MfGMs6MA77+BduAWn7FV7e1qxfR78MNupa6iV4retGfE898EMqvzUTVlhjUwb8pTioggFJbrG5pphLTqOL5FsLpZ/+Xbq49CyXhyygs=,iv:1Z+hbQ1FldUmrlcqX+ElYpB36SlFaUeibo61mSCQMfM=,tag:VLcMSguHBA/OKADmgA+2mA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
