apiVersion: ENC[AES256_GCM,data:15c=,iv:qNdfi26pyPsD+4NQqhrcUh/uW+DbPlxyUSzq5MCrlaU=,tag:sgHj45phulpadYAlWfjPMw==,type:str]
kind: ENC[AES256_GCM,data:AaW39az4,iv:/mYMGTO0Vlpo9isyob7nw95i8TC+GSoEueLuLAVd78A=,tag:rg8LHi2+XLwoIiQaX6CUQw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tWfj8fWCnIjfIdXWVKWPXwsqKw==,iv:I2JwH8tE3LLPXl+QPKqOfxBbgdeMFJcPNoq6u7Og0Vw=,tag:cvdBz62wYWkqwnyrBdv4bQ==,type:str]
    namespace: ENC[AES256_GCM,data:dLHjA39GP7lf,iv:eY6J6LyAhqTl4fDAyxD9dhY9kQb59w+LuFEnBUN0Hpk=,tag:bFaBz/UpVyT1V6IcIY/mZg==,type:str]
type: ENC[AES256_GCM,data:HlFtcJ5p,iv:uD7MhUDcMqTbyVMEJS9xHTHgKyNApEC1k5YswM+PVfI=,tag:aeQJDWIMRxwhtri4NVYSTA==,type:str]
stringData:
    WHITELIST: ENC[AES256_GCM,data:qjK9NpIatafj9Rc2ESaUrkE5vRLHhiGfeg==,iv:0CvJ3hFzeeOdjlYWLlpWR73GqlTqEoDt4dPTqUVF80M=,tag:OWRMmRD+PWtIcQZUE4ySRQ==,type:str]
    OPS: ENC[AES256_GCM,data:C+bftPBfwA==,iv:VdVrlq6xL3kBfEcLjIPFK4IJZXk7g84vs2jtrf8NCFw=,tag:/veCpAQax2/dd+vCg2aUfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUU1Cc0RLaFI5MzZjWDZR
            aVdCYkJLcGRKVGt2NTJpc1Q3ci9CL0NiZ1c0CmpQQ1dIVTRhRFpuci9JM1FBci9a
            N005SGxFWkV2dUluYmFjbjdiMHZsUzAKLS0tIGFjOTRmeFQ1Ymw0dVZmampLYndo
            djlqVHRzUHdDZzBIeDVYengxcWtZL3cKVjPiKs001cRHAzVxzBjky05UZpD1X58V
            e1l4PTUtLZyC2rcsE6TJ4/MIje9gDwFDqOcTJyorcWPxnMWY3LD2Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-08-02T21:57:55Z"
    mac: ENC[AES256_GCM,data:VaEl3AEsu3AxPzhWXv/NEsk05MabbmTiHj9plaPV5dy2aQexn3PCraXSxAxzQ6LYj2/itWozfG3ZmBP5KtivD3xhSR9LtkJoYZTdzmRcp7U/hDH5SScPiSZPrloR7wWfAm0rGIevbNJr8Gg5hfm+3rDYlejX2gzd9VjBZWK7gpA=,iv:YXsI82Hlp3Wv7BySW50hLJUc2E3uHorTp1Yw9e9JhUM=,tag:4MEjoSN1dVV5TvuO4fBKmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
