apiVersion: dns.upjet-cloudflare.m.upbound.io/v1alpha1
kind: Record
metadata:
  name: mc-tylerrosnett
  namespace: cloudflare
spec:
  forProvider:
    zoneId: 44d494598f8397dcf5b600cc3c41455c
    name: mc
    type: A
    content: 47.151.137.156
    ttl: 300
    proxied: false  # raw TCP — must stay DNS-only, CF proxy would break it
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
