apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blocky
  namespace: blocky
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: blocky
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
