apiVersion: v1
kind: Service
metadata:
  name: blocky-metrics
  namespace: blocky
  labels:
    app: blocky
spec:
  type: ClusterIP
  selector:
    app: blocky
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
