apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    lb-announce: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.203
  selector:
    app: minecraft
  ports:
    - name: minecraft
      port: 25565
      targetPort: minecraft
      protocol: TCP
