apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: hello-public-ingress
  namespace: hello-public
spec:
  endpointSelector:
    matchLabels:
      app: hello
  ingress:
    - fromEntities:
        - host
        - remote-node
