apiVersion: ENC[AES256_GCM,data:MkM=,iv:kDO9SgFZY1g4BdjVDJEWqpHUNMlFH/+q5zP0bMsLAWI=,tag:NCEJ0eV9+lVgZ/QpPxjQhA==,type:str]
kind: ENC[AES256_GCM,data:fmiAaP49,iv:0k/QBH5bpMICdjmJKG6FwqeASGKA5W/JgvOI5DRFIok=,tag:hJWbiZIBgY93um68LFN4bQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MjG7UoGPG9XvpSoJerKipyNXdrT7Go28ppitIDfkag==,iv:CR4c4Cq9m4J9f2AU7kzZaDEGkMnfZxEUnvgxef+XVac=,tag:o3XZ6fmfNsGzgwsnAffHgA==,type:str]
    namespace: ENC[AES256_GCM,data:vWMFhpyAaNac4WLRPRg=,iv:hOuk0/gKhrvLmUiOypZbY0Tw7OYnpipIdJJwes8gFlU=,tag:r350YPjpYUjmnOi2lS6cDQ==,type:str]
type: ENC[AES256_GCM,data:uDWZUt1D,iv:n79JREzzd7ZAMTAXZQvqpRviylucLdMXjB8EfbVCbH0=,tag:WYNVO/WTRvcj7605BN/VFw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:nGERolUJalNV9YnE2jScLFt1CzYit8GByakpZ4rh4YxYL3YDDBE1hXRLANkeVQuxrlhA4Fe7N+dg9Jv2nFhjAlK7X67rKkZf7uyQcdnWrH6jwvAmYvWWp9X2T0RM2iB8lQVWIE8J/ZzxNgFOCTjsqAW/0COevywrYMHv3h15z06zPbKIW0/2FtCa7+gsuZSflr0pgPO79ITRArExX8MQ6urDT+ErnzRHUx/+Qkwh4QFuvA7s/xDR,iv:D+JaVJTDRQIpPhj949ahgEba+XX8aCR7RZrxxDhabdM=,tag:OxBr/srDB2iDQBVBGH0pqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbC9neEZ4SncwUXNYZ2NZ
            WW5TZm1VVWZqTklEZjl0WWZtZm1ZQWRNem5FCkx3TWFKRENFcmJSYlh4MmM4MjQ2
            ZWIyL09NRWoraEQ5eDhDRTI1eTNpNUkKLS0tIE9tUVpSRUZRUDhmYlFiZk5Td2VX
            c25NWTN1ZEZsYU1oQVk2TTl3T3RNV00KYRQg7anMf11Tk11G4dx1G8O7jO0jvnGP
            rnZX2GGVgCaiO/8tMftKjXysliwLbGG9+zHWZT8UBMjSpZ7VFl7AFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-06-05T04:09:54Z"
    mac: ENC[AES256_GCM,data:ujNISMylTCfec3zMrAqW+dwAzm8qknU5vt4ChUUfw2B80WJp6LqsbMqGmNxMM49NfgFFrq2G8hgbo92oqGqZxUZFaLryVjxLFPDKpoNbZqV530YzIK7nhwA+QvWaTREv1xH0s/+5bTa7MN6jJEiuUmgLtBA9EGgnl7noYEVs5kA=,iv:ppj+E74HIN/4p6V23y+XBeHAPxouGwprlAmVDh1dXAc=,tag:kxwiUVesyUFb3jo93yYl7Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
