apiVersion: ENC[AES256_GCM,data:X+MLhrNMah7ivqJz3eeVlNSRqIoC2hy/JygkYQ==,iv:H/BwbPB/W2RQerVNrWFSEqEenYyqmAcHXfnfJZ+9xyI=,tag:shanTF4KxQn4uEchNAAvvQ==,type:str]
kind: ENC[AES256_GCM,data:7A1NBdKZBwtQSAShjfnU142T,iv:QOrIO/DI2745dzJft6byR8L9OfPy3G/DU8qOlIa49mk=,tag:LViL/7Ym+ZyxuH3PqTRrVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:c2PvuVV+hpeEc9BHi5qiCy7d,iv:QN4pVQ8qjJ3u6hAldCE7fO42yXenJewqeUZStofUl28=,tag:J1H/V9e1XCMukygGLO7/Mw==,type:str]
subjects:
    - kind: ENC[AES256_GCM,data:usXhEg==,iv:p1yuKHjgPVkKAyIaQJSwMc/4ipPNjbFPxWcDFkEFE0Y=,tag:e+hzNJV3Wvm9qwVjauo93w==,type:str]
      name: ENC[AES256_GCM,data:qbanxHn6ducwqxlASKyxXzaBwUFYzQ==,iv:eM3TjiGkA4/rHhYc9KsyDK2d4tRrQED0NasZUCa6yWI=,tag:17Xh1HgxGiSxlEB3CidMtg==,type:str]
      apiGroup: ENC[AES256_GCM,data:zjFIIe3NBqWp50XtLM5OFkqmq3xCXVgFTA==,iv:N79+rh+RKrRts5hjhyNNznvb7VZO6wNsz2qZ5S32CQ4=,tag:qw8RRC0/KuaXDqterrqpvw==,type:str]
roleRef:
    kind: ENC[AES256_GCM,data:peYdWEXoN8F5D0Q=,iv:M7dUVaM4zzQTd5YDryOS7qgCuQa1+5BLwfKoBZkKBM4=,tag:Zh+5leNjlPZLIhxtNrqMYA==,type:str]
    name: ENC[AES256_GCM,data:fugqQIal5azGb5wMog==,iv:11ympC9ESn8E9HOBu93sgnn/eMN3Ww9jzwPgqSWS8cI=,tag:huyJPBvfHMv1nu8wi5P3JQ==,type:str]
    apiGroup: ENC[AES256_GCM,data:qU4G4xR+YJ2+XfWIthvCjfWnPf9H/1Wwcw==,iv:/HoBlzcVsMQPE4r/taCN5qv+yugpjjj4dtURxywx8ZM=,tag:cN3qZQHMlfA0BvjUYrwBAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bEpra0RYUTNHTTAvczNj
            ZlFRa2Rja1cwYlRURUY5NDMxcG9BZE9hZVZvCjV2ZUIvdDNKRmV5WE5USUh2QS91
            eTllZjJxLzQ1T25qblJGQkg3NGJEUWsKLS0tIFRiUEdmZUljUUlzendqUTM4Q0lO
            RFlNcUJtYVRVM3RFKzBTZFhtakE5M0EKCtfgycYMgLf2paMfogZip0a44EoIsO6k
            3T83mjQ0FCpDFW9BGm6Gz92LaIWhE/Va8AWKWzS0Wgiw6RnMhb0doQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-05-19T02:33:19Z"
    mac: ENC[AES256_GCM,data:fxodMM5faCbvDwCjoxf2t95g41qMwvJrOP+LZNzqz20fqNvoBy7eKT2zvcv1jF+VNTuLxKk8cyzgPovQnCJMq+xcXWUwmbv9TxxEPXh5xDA3taKYxOeoQcL4e54iUtNtl7xvt5LSqWjP3/aKxhKBPGqf225wGpr5onzEp2Pa1Co=,iv:6V1HILEZ59ewxBSfu9qdGSBIpW7rQXGNdqDbFR/1kMg=,tag:71ySCSjeNcBIfMWo7DBs1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
