apiVersion: ENC[AES256_GCM,data:ClELetJkWsi/1t2ueA5gluoUYkrEzYe30zVnNg==,iv:MhfnH+WJD1wxWkOq657gH5rFPDvufezuCE6iZXWLlrA=,tag:UMPjXCL/7M/mcNQTi43AlQ==,type:str]
kind: ENC[AES256_GCM,data:V/6huFCLAKDRgvPU7HC5pdiV,iv:Vce0/ha7AfJSxz/I5q5X6TF8nbPhHCiQ8NctFSj6VM0=,tag:3R4zEOtk5CfjKmKuMoLhiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tzwGZrmLWu1mWY/GYJm/JFn/LYwSntmUztw3YA==,iv:Fr/5ffPMwfZvFagagSY2XwJ5b4Gq88nMvGnwpL/ViHg=,tag:2HxVpkrBpbtBWUnhfvZKbg==,type:str]
roleRef:
    apiGroup: ENC[AES256_GCM,data:RGOLabubdnAabU6SPIhRxszkfdrXnWizvA==,iv:jdwFGYlodFF53u/zfe9WQP6ZlfYSahy6abruIRX4trA=,tag:lfqi5CPAWFlU2Fej/id3Cw==,type:str]
    kind: ENC[AES256_GCM,data:bLVKTrHkzFoyZ9Q=,iv:+NmVIf/yQ8vcveA2+h/sMQ9Jf6nBjPSCAXO5+LOec7o=,tag:SmiajIfFSzw0gaW0XzIG3Q==,type:str]
    name: ENC[AES256_GCM,data:GrpcR9DhoB/3N2g+Kg==,iv:R98qT1DE2ACwEXgjNA6xg+p3Wc1gWLs18Y1B42/3JLw=,tag:S6/VvIyt/1/ThEWemvQUog==,type:str]
subjects:
    - kind: ENC[AES256_GCM,data:9DAqPtI=,iv:6zAiSbOUaQ9HXgIVtz4kOjUjs55VNHZ5Qd33y0WCV2A=,tag:5WcLU+UCuq1Bx9G9WkCD7w==,type:str]
      apiGroup: ENC[AES256_GCM,data:F4YqKAuANRhI1ErBL/ePqb+kN6hQAd/gCg==,iv:NZ75dirv8n595Jy5CHtjYahZTYNfw+M7w+xyX7GavWw=,tag:7BqZgHXL0WRQhqA3ndVELg==,type:str]
      name: ENC[AES256_GCM,data:HZYTpWHWL1cl,iv:Mk6cVdQRmamE24KrIvdqWose6Oj2yqfO/IkCbXf6u9Y=,tag:aeLg3eSFwDGgTnnhkNf/Xw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcUFZTUt0bmZ1OXNYRWlp
            bCtuWlMxREswMTdzOTM3RC9QbGY5NnUyN0U0CnQvUExsM1V3MzlMVE1rczNRdC85
            aXk4eXEzKzdpeW5QOWdGcG1IMWlTUTQKLS0tIG9QZHdwWHAxY0RYUkxDaWJXLzc4
            cnptTGtiVEVNNE93WGxieGxRcHpRWncKZGOKbkw1WT704X2ij2TD8jUz5s4UHMf7
            JXH4DGBuRCftr779EFuDEn09NYQePKLvwNDlJ81bahFNMpsT83dGHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1seegwzyg0ldnm2jerlpsyzkcrqctytqthwdpf0h9fs20w4nngqlqsvpaa0
    lastmodified: "2026-05-20T20:15:19Z"
    mac: ENC[AES256_GCM,data:eGtK5Dx6ax6uc71LVQpDw4g+sf6vZx5oIp7Oas2QH0a6Tb7eWFQlDJ+Ijhp6zX/yuHBB5Rco4ZMT+a42T+n32ANHosQ406m/UWgkM0L+3jIxvs/YwOKtAc0VQNbBs9NZHcTLnWvScUIY1uQNofQLhlEtA5MQk65Bt2W87PbCsSE=,iv:1e2qYkIZ00YI2KkEv/SacJzIARtqMT0lN0k7+cF9xes=,tag:axtw1ZHT49NSQbFOMJoPJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
